### ISSUE TITLE
context.report error

### ISSUE THREAD

**Issue by alexandervalencia** [liferay/liferay-frontend-source-formatter#23]
Running csf on other FTL files in my theme worked fine but I hit an error when trying to run against portal_normal.ftl

Stacktrace:
```
Unhandled rejection TypeError: context.report() called with a messageId, but no messages were present in the rule metadata.
    at /usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/report-translator.js:260:23
    at Object.report (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/linter.js:945:62)
    at checkComputedProperty (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/rules/dot-notation.js:77:25)
    at Object.MemberExpression (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/rules/dot-notation.js:116:21)
    at MemberExpression (/usr/local/lib/node_modules/check-source-formatting/lib/lint_js_rules/dot_notation.js:11:32)
    at listeners.(anonymous function).forEach.listener (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/linter.js:1006:32)
    at Traverser._traverse (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/traverser.js:132:14)
    at Traverser._traverse (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/traverser.js:147:30)
    at Traverser._traverse (/usr/local/lib/node_modules/check-source-formatting/node_modules/eslint/lib/util/traverser.js:147:30)
```

**Comment by natecavanaugh** [comment]
Thanks for the report @alexandervalencia . I tested it against the file you sent and can't reproduce it at all.

What version of the formatter are you running? And what's your node version?

**Comment by alexandervalencia** [comment]
CSF: 2.0.4
Node: 6.12.0
NPM: 3.10.10

**Comment by natecavanaugh** [comment]
@alexandervalencia This is so strange... I have switched over to node 6.12.0, and still can't reproduce the error.

Do you have any config setup anywhere, like in your package.json or a csfConfig.js file somewhere in the parent directories?

Worst case scenario, have you tried uninstalling it and reinstalling it? I'm only wondering if there's a dependency that was cached wrongly during the last upgrade?

Might be worth a shot...
